name: Build postmarketOS Image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-pmos:
    runs-on: ubuntu-latest

    env:
      DEVICE: "xiaomi-miatoll"     # Change to your device
      ARCH: "aarch64"
      BOOT_SIZE_MB: 1024           # 1 GB boot partition

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git curl wget unzip python3-pip dosfstools e2fsprogs \
            qemu-user-static kpartx pv lz4 device-tree-compiler liblz4-tool \
            parted xz-utils squashfs-tools bzip2 zip
          # Do not upgrade wheel – avoids Debian uninstall error
          sudo pip3 install --upgrade pip setuptools

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Clone pmbootstrap
        run: git clone https://gitlab.com/postmarketOS/pmbootstrap.git ~/pmbootstrap

      - name: Initialize pmbootstrap
        run: |
          cd ~/pmbootstrap
          ./pmbootstrap init --device $DEVICE --arch $ARCH --mirror-alpine-edge --no-interaction
          ./pmbootstrap config apks add nano htop

      - name: Customize boot partition size
        run: |
          mkdir -p ~/.config/pmbootstrap/
          echo 'export BOOT_SIZE_MB="$BOOT_SIZE_MB"' > ~/.config/pmbootstrap/custom.sh
          echo "Custom 1GB /boot size set (manually edit partition later if needed)"

      - name: Build postmarketOS image
        run: |
          cd ~/pmbootstrap
          ./pmbootstrap install
          ./pmbootstrap export

      - name: Zip image output
        run: |
          cd ~/pmbootstrap
          mkdir -p out
          zip -r out/postmarketos-${{ env.DEVICE }}.zip pmboutput/

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: postmarketos-image
          path: ~/pmbootstrap/out/postmarketos-${{ env.DEVICE }}.zip
