name: Build postmarketOS Image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-pmos:
    runs-on: ubuntu-latest

    env:
      DEVICE: "xiaomi-miatoll"   # or your device code
      ARCH: "aarch64"
      BOOT_SIZE_MB: 1024         # 1G boot partition

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git curl wget unzip python3-pip dosfstools e2fsprogs \
            qemu-user-static kpartx pv lz4 device-tree-compiler liblz4-tool \
            parted xz-utils squashfs-tools bzip2 zip
          sudo pip3 install --upgrade pip setuptools wheel

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Clone pmbootstrap
        run: git clone https://gitlab.com/postmarketOS/pmbootstrap.git ~/pmbootstrap

      - name: Initialize pmbootstrap
        run: |
          cd ~/pmbootstrap
          ./pmbootstrap init --device $DEVICE --arch $ARCH --mirror-alpine-edge
          ./pmbootstrap config apks add nano htop
          echo "Configured for $DEVICE"

      - name: Customize boot partition size
        run: |
          mkdir -p ~/.config/pmbootstrap/
          echo 'BOOT_PARTITION_SIZE_MB="$BOOT_SIZE_MB"' > ~/.config/pmbootstrap/custom.cfg

      - name: Build image
        run: |
          cd ~/pmbootstrap
          ./pmbootstrap install
          ./pmbootstrap export

      - name: Create ZIP of image
        run: |
          cd ~/pmbootstrap
          mkdir -p out
          zip -r out/postmarketos-${{ env.DEVICE }}.zip pmboutput/

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: postmarketos-image
          path: ~/pmbootstrap/out/postmarketos-${{ env.DEVICE }}.zip
