name: Build images

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 5'

env:
  KERNEL_BRANCH: 6.12.1

jobs:
  build-image:
    strategy:
      matrix:
        version: ["default"]

    runs-on: ubuntu-latest

    steps:
      - name: Check out build configurations
        uses: actions/checkout@v4

      - name: Substitute placeholders in configs
        run: |
          find . -type f -name "*.cfg" -exec sed -i "s|HOME|$(echo $HOME)|;s|NPROC|$(nproc)|" {} +

      - name: Install pmbootstrap from git
        run: |
          git clone --depth=1 https://gitlab.postmarketos.org/postmarketOS/pmbootstrap.git
          mkdir -p ~/.local/bin
          ln -s "$PWD/pmbootstrap/pmbootstrap.py" ~/.local/bin/pmbootstrap
          pmbootstrap --version

      - name: Set up pmaports
        run: |
          echo -e '\n\nedge\nfairphone\nfp4\n\n\nphosh\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n' | pmbootstrap init || true
          cd ~/.local/var/pmbootstrap/cache_git/pmaports
          git remote add 99degree https://github.com/99degree/pmaports.git
          DEFAULT_BRANCH=$(git remote show sm7125 | awk '/HEAD branch/ {print $NF}')
          git fetch 99degree $DEFAULT_BRANCH
          git checkout 99degree/next -- main/adbd-linux

      - name: Check kernel branch
        if: matrix.version == 'default'
        run: |
          DEFAULT_BRANCH=$(curl -s https://api.github.com/repos/sm7125-mainline/linux | jq -r '.default_branch')
          echo "Default branch is $DEFAULT_BRANCH"
          echo "KERNEL_BRANCH=$DEFAULT_BRANCH" >> $GITHUB_ENV

      - name: Choose Miatoll config
        run: cp xiaomi-miatoll.cfg ~/.config/pmbootstrap_v3.cfg

      - name: Create artifact directory
        run: mkdir -p out

      - name: Build xiaomi-curtana with 1GB boot
        run: |
          cp xiaomi-miatoll.cfg ~/.config/pmbootstrap_v3.cfg
          pmbootstrap build adbd-linux
          pmbootstrap config extra_packages adbd-linux
          pmbootstrap install --password 147147 --split
          pmbootstrap export
          ls -la /tmp/postmarketOS-export/

          # Copy and pad boot.img to 1GB
          BOOTIMG="/tmp/postmarketOS-export/xiaomi-miatoll-boot.img"
          PADDED="out/boot-xiaomi-tianma-miatoll.img"

          if [ -f "$BOOTIMG" ]; then
            cp "$BOOTIMG" "$PADDED"
            ACTUAL_SIZE=$(stat --format="%s" "$PADDED")
            TARGET_SIZE=1073741824
            if [ "$ACTUAL_SIZE" -lt "$TARGET_SIZE" ]; then
              dd if=/dev/zero bs=1 count=$((TARGET_SIZE - ACTUAL_SIZE)) >> "$PADDED"
            fi
          fi

          # Copy all other images
          cp /tmp/postmarketOS-export/*miatoll*.img out/ || true

          # Clean up chroots
          echo -e "n\nn\ny\n" | pmbootstrap zap

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: xiaomi-curtana-${{ env.KERNEL_BRANCH }}
          path: out/*-miatol*.img*
          retention-days: 7
